commands:

  # Hora
  - command:
    input: Que horas são?
    entity: time
    action: getTime
  - command:
    input: São que horas?
    entity: time
    action: getTime
  - command:
    input: Hora
    entity: time
    action: getTime

  # Data
  - command:
    input: Que dia é hoje?
    entity: time
    action: getDate
  - command:
    input: Qual a data de hoje?
    entity: time
    action: getDate
  - command:
    input: Data
    entity: time
    action: getDate

  # Clima
  - command:
    input: Previsão do tempo
    entity: weather
    action: getWeather
  - command:
    input: Como está o clima?
    entity: weather
    action: getWeather

  # Abrir
  - command:
    input: Abrir Brave
    entity: open
    action:
  - command:
    input: Iniciar Brave
    entity: open
    action: